networks:
  proxy:
    external: true
    name: proxy
services:
  app:
    container_name: sonarr
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/London
    image: ghcr.io/linuxserver/sonarr
    labels:
      traefik.enable: "true"
      traefik.http.routers.sonarr.entrypoints: web
      traefik.http.routers.sonarr.rule: Host(`sonarr.docker`)
      traefik.port: '8989'
    networks:
      proxy: {}
    ports:
    - published: 8989
      target: 8989
    restart: unless-stopped
    volumes:
    - /mnt/docker_configs/sonarr:/config:rw
    - /mnt/Shared/downloads:/downloads:rw
    - /mnt/Shared/multimedia/tv:/tv:rw
version: '3.4'

