networks:
  proxy:
    external: true
    name: proxy
services:
  app:
    container_name: qbittorrent
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/London
      WEBUI_PORT: '8080'
    image: lscr.io/linuxserver/qbittorrent:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.qbittorrent.entrypoints: web
      traefik.http.routers.qbittorrent.rule: Host(`qbittorrent.docker`)
      traefik.port: '8080'
    networks:
      proxy: {}
    ports:
    - published: 6881
      target: 6881
    - protocol: udp
      published: 6881
      target: 6881
    - published: 8080
      target: 8080
    restart: unless-stopped
    volumes:
    - /mnt/docker_configs/qbittorrent:/config:rw
    - /mnt/Shared/downloads:/downloads:rw
version: '3.4'

