name: qbittorrent
services:
  qbittorrent:
    container_name: qbittorrent
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
      WEBUI_PORT: "8080"
    image: lscr.io/linuxserver/qbittorrent:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.qbittorrent.entrypoints: web
      traefik.http.routers.qbittorrent.rule: Host(`qbittorrent.docker`)
      traefik.port: "8080"
    networks:
      proxy: null
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
      - mode: ingress
        target: 6881
        published: "6881"
        protocol: tcp
      - mode: ingress
        target: 6881
        published: "6881"
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /mnt/docker_configs/qbittorrent
        target: /config
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/Shared/downloads
        target: /downloads
        bind:
          create_host_path: true
networks:
  proxy:
    name: proxy
    external: true
