---
version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall_2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/docker_configs/heimdall:/config
    ports:
      - 74:80
      - 234:443
    restart: unless-stopped
    networks:
      - proxy_net
networks:
        proxy_net:
           name: mg_network
