networks:
  proxy:
    external: true
    name: proxy
services:
  app:
    container_name: readarr
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/London
    image: lscr.io/linuxserver/readarr:develop
    labels:
      traefik.enable: "true"
      traefik.http.routers.readarr.entrypoints: web
      traefik.http.routers.readarr.rule: Host(`readarr.docker`)
      traefik.port: '8787'
    networks:
      proxy: {}
    ports:
    - published: 8787
      target: 8787
    restart: unless-stopped
    volumes:
    - /mnt/Shared/multimedia/books:/books:rw
    - /mnt/docker_configs/readarr:/config:rw
    - /mnt/Shared/downloads:/downloads:rw
version: '3.4'

