networks:
  proxy:
    external: true
    name: proxy
services:
  app:
    container_name: prowlarr
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/London
    image: lscr.io/linuxserver/prowlarr:develop
    labels:
      traefik.enable: "true"
      traefik.http.routers.prowlarr.entrypoints: web
      traefik.http.routers.prowlarr.rule: Host(`prowlarr.docker`)
      traefik.port: '9696'
    networks:
      proxy: {}
    ports:
    - published: 9696
      target: 9696
    restart: unless-stopped
    volumes:
    - /mnt/docker_configs/prowlarr:/config:rw
    - /mnt/Shared/downloads:/downloads:rw
version: '3.4'

