networks:
  proxy:
    external: true
    name: proxy
services:
  app:
    container_name: plex
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/London
      VERSION: docker
    image: ghcr.io/linuxserver/plex
    labels:
      traefik.enable: "true"
      traefik.http.routers.plex.entrypoints: web
      traefik.http.routers.plex.rule: Host(`plex.docker`)
      traefik.port: '32400'
    networks:
      proxy: {}
    ports:
    - published: 32400
      target: 32400
    restart: unless-stopped
    volumes:
    - /mnt/docker_configs/plex:/config:rw
    - /mnt/Shared/downloads:/downloads:rw
    - /mnt/Shared/multimedia:/movies:rw
version: '3.4'

