
---
version: "2.1"
services:
  plex:
    extends:
      file: ../common-services.yml
      service: common_service
    image: ghcr.io/linuxserver/plex
    container_name: plex
    # network_mode: host
    environment:
      - VERSION=docker
    volumes:
      - /mnt/Shared/multimedia:/movies
