networks:
  proxy:
    external: true
    name: proxy
services:
  app:
    container_name: airsonic
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/London
    image: ghcr.io/linuxserver/airsonic
    labels:
      traefik.enable: "true"
      traefik.http.routers.airsonic.entrypoints: web
      traefik.http.routers.airsonic.rule: Host(`airsonic.docker`)
      traefik.port: '4040'
    networks:
      proxy: {}
    ports:
    - published: 4040
      target: 4040
    restart: unless-stopped
    volumes:
    - /mnt/docker_configs/airsonic:/config:rw
    - /mnt/Shared/downloads:/downloads:rw
    - /mnt/Shared/multimedia/muzyka:/music:rw
version: '3.4'

