 services:
   traefik:
     restart: always
     image: traefik:v3.0
     container_name: traefik
     ports:
       - 81:80
       - 8081:8080
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
       - ./traefik.toml:/etc/traefik/traefik.toml
     networks:
       - proxy
 networks:
   proxy:
     name: proxy 
     external: true
