---
version: "2.1"
services:
  radarr:
    extends:
      file: ../common-services.yml
      service: common_service
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    volumes:
      - /mnt/Shared/downloads:/downloads
      - /mnt/Shared/multimedia/movies:/movies
networks:
    proxy:
        external: true
