version: "2.1"
services:
    grocy:
        image: ghcr.io/linuxserver/grocy:version-v2.7.1
        container_name: grocy
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - /mnt/docker_configs/grocy:/config
        ports:
            - 9283:80
        restart: unless-stopped
        networks:
            - proxy_net
networks:
        proxy_net:
           name: mg_network

