version: "2.1"
services:
  minecraft_server:
    image: itzg/minecraft-server
    container_name: mc_server
    environment:
      - EULA=TRUE
    volumes:
      - /mnt/docker_configs/minecraft2/:/data
    ports:
        - 25565:25565
    restart: unless-stopped
