networks:
  proxy:
    external: true
    name: proxy
services:
  app:
    container_name: lidarr
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/London
    image: ghcr.io/linuxserver/lidarr
    labels:
      traefik.enable: "true"
      traefik.http.routers.lidarr.entrypoints: web
      traefik.http.routers.lidarr.rule: Host(`lidarr.docker`)
      traefik.port: '8686'
    networks:
      proxy: {}
    ports:
    - published: 8686
      target: 8686
    restart: unless-stopped
    volumes:
    - /mnt/docker_configs/lidarr:/config:rw
    - /mnt/Shared/downloads:/downloads:rw
    - /mnt/Shared/multimedia/music:/music:rw
version: '3.4'

