---
version: "2.1"
services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/docker_configs/lidarr:/config
      - /mnt/Shared/multimedia/muzyka:/music
      - /mnt/Shared/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
