---
version: "2.1"
services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/docker_configs/lidarr:/config
      - /mnt/Shared/multimedia/muzyka:/music
      - /mnt/Shared/downloads:/downloads
    ports:
      - 8686:8686
    labels:
      - traefik.enable=true
      - traefik.http.routers.apache.rule=Host(`lidarr.docker`)
      - traefik.http.routers.apache.entrypoints=web
      - traefik.port=8686
    networks:
      - proxy
    restart: unless-stopped

networks:
    proxy:
        external: true
