---
version: "2.1"
services:
  lazylibrarian:
    image: ghcr.io/linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - /mnt/docker_configs/lazyLibrarian_config:/config
      - /mnt/Shared/downloads:/downloads
      - /mnt/Shared/books:/books
    ports:
      - 5299:5299
    restart: unless-stopped
