networks:
  proxy:
    external: true
    name: proxy
services:
  app:
    container_name: transmission
    environment:
      PASS: mg
      PGID: '1000'
      PUID: '1000'
      TRANSMISSION_WEB_HOME: /transmission-web-control/
      TZ: Europe/London
      USER: mg
    image: ghcr.io/linuxserver/transmission
    labels:
      traefik.enable: "true"
      traefik.http.routers.transmission.entrypoints: web
      traefik.http.routers.transmission.rule: Host(`transmission.docker`)
      traefik.port: '9091'
    networks:
      proxy: {}
    ports:
    - published: 9091
      target: 9091
    - published: 51413
      target: 51413
    - protocol: udp
      published: 51413
      target: 51413
    restart: unless-stopped
    volumes:
    - /mnt/docker_configs/transmission:/config:rw
    - /mnt/Shared/downloads:/downloads:rw
    - /mnt/docker_configs/transmission/watch:/watch:rw
version: '3.4'

