version: "2.1"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
      - USER=mg
      - PASS=mg
    volumes:
      - /mnt/docker_configs/transmission:/config
      - /mnt/Shared/downloads:/downloads
      - /mnt/Shared/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
