version: "3"
services:
  app:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
      - USER=mg
      - PASS=mg
    volumes:
      - /mnt/docker_configs/transmission/watch:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp
